import { Dispatch, SetStateAction } from "react";
import PropertiesController from "./PropertiesController";
import firestore from "@react-native-firebase/firestore";
import { MMKV } from "react-native-mmkv";


/* type alias for the RN update hook */
export type HookType = {
  variable: boolean,
  setter: Dispatch<SetStateAction<boolean>>
};

/* Flags to specify the capabilities of a controller */
export enum Flags {
  requires_id =     0b00001,
  has_trail =       0b00010,
  can_deactivate =  0b00100,
  can_delete =      0b01000,
  can_update =      0b10000,
}

export default class BaseController {
  /* properties controller of the collection */
  private readonly propertiesInstance?: PropertiesController;

  /* collection name */
  private readonly collection_name: string;

  /* firestore instance representing the database */
  private readonly serverInstance: typeof firestore;

  /* MMKV storage instance used for the controllers */
  private readonly storageInstance: MMKV;

  /* flags variable generated by applying logical or on Flag enums */
  private readonly flags: number;

  /* update hook used to trigger front-end updates */
  private readonly update_hook: HookType;

  /**
   * @param collection_name name of the controlled collection
   * @param server firestore instance for the database
   * @param update_hook RN update hook for front-end updates
   * @param flags number representing capabilities of controller
   * @param properties properties controller for the collection
   */
  public constructor(collection_name: string,
              server: typeof firestore,
              update_hook: HookType,
              flags: number = 0,
              properties?: PropertiesController) {
    this.propertiesInstance = properties;
    this.collection_name = collection_name;
    this.serverInstance = server;
    this.flags = flags;
    this.update_hook = update_hook;
    this.storageInstance = new MMKV({
      id: `${firestore.name}-${collection_name}-mmkv`,
      encryptionKey: collection_name
    });
  }

  /**
   * @returns PropertiesController of the controller
   */
  public get properties() {
    return this.propertiesInstance;
  }

  /**
   * @returns the collection name
   */
  public get collectionName() {
    return this.collection_name;
  }

  /**
   * @returns the firestore instance
   */
  public get server() {
    return this.serverInstance;
  }

  /**
   * @returns the MMKV storage instance
   */
  public get storage() {
    return this.serverInstance;
  }

  /**
   * @returns the RN hook instance
   */
  public get hook() {
    return this.update_hook;
  }

  /**
   * @returns true if the controller requires IDs
   */
  public get requiresId(): boolean {
    return (this.flags & Flags.requires_id) !== 0;
  }

  /**
   * @returns true if the controller requires a trail
   */
  public get hasTrail(): boolean {
    return (this.flags & Flags.has_trail) !== 0;
  }

  /**
   * @returns true if the controller can deactivate entities
   */
  public get canDeactivate(): boolean {
    return (this.flags & Flags.can_deactivate) !== 0;
  }

  /**
   * @returns true if the controller can delete entities
   */
  public get canDelete(): boolean {
    return (this.flags & Flags.can_delete) !== 0;
  }

  /**
   * @returns true if the controller can update entities
   */
  public get canUpdate(): boolean {
    return (this.flags & Flags.can_update) !== 0;
  }
}
