import firestore, { FirebaseFirestoreTypes } from "@react-native-firebase/firestore";
import { MMKV } from "react-native-mmkv";
import { create, insert, Orama, ProvidedTypes, remove, Schema } from "@orama/orama";
import {
  IdAlreadyExistsError,
  IdDoesNotExistError,
  NoDataError,
  NoDeactivateError,
  NoDeleteError,
  NoTrailError,
  NoUpdateError, PivotError
} from "./Errors";
import { Generic, SpecialFields, TrailNature, TrailType } from "../model/types";
import BaseModel from "../model/BaseModel";
import CollectionNames from "./CollectionNames";
import { identity, isEqual, isInteger, pickBy } from "lodash";
import { reduxStorage } from "../../../store";


/* Flags to specify the capabilities of a controller */
export enum ControllerFlag {
  pivot_not_list =  0b00001,
  has_trail =       0b00010,
  can_deactivate =  0b00100,
  can_delete =      0b01000,
  can_update =      0b10000,
}

/**
 * Class responsible for handling raw data storage & retrieval
 * from the cache and database.
 * Forms the base class for the rest of the controllers.
 */
export default abstract class BaseController<RawData extends Generic> {
  /* collection name */
  private readonly collection_name: string;

  /* name of the ID list collection */
  private static readonly id_list_collection_name: string = CollectionNames.ids;

  /* name of the data field representing a document ID */
  private readonly collection_id: string;

  /* firestore instance representing the database */
  private readonly serverInstance: typeof firestore;

  /* MMKV storage instance used for the controllers */
  private readonly storageInstance: MMKV;

  /* set of all collection IDs */
  private idSetInstance: Set<string>;

  /* pivot ID for the documents */
  private pivotValue: number;

  /* flags variable generated by applying logical or on Flag enums */
  private readonly flags: number;

  /* search engine instance for the controller */
  public searchEngine?: Orama<ProvidedTypes>;

  /* cached dependencies */
  // TODO Fix dependency injections
  private static dependencies = {};

  /* maps document IDs to Orama IDs */
  private idToOramaId: {
    [id: string]: any
  } = {};

  /**
   * @param collection_name name of the controlled collection
   * @param collection_id name of the data field
   *        that acts as an ID for the document.
   *        This field is removed from raw data on upload & download.
   * @param server firestore instance for the database
   * @param search_schema for the search engine
   * @param flags number representing capabilities of controller
   */
  protected constructor(collection_name: string,
              collection_id: string,
              server: typeof firestore,
              flags: number = 0,
              search_schema?: Schema) {
    if (search_schema !== undefined) {
      create({
        schema: search_schema,
        id: collection_name
      }).then((value) => {
        this.searchEngine = value;
      });
    }

    this.idSetInstance = new Set<string>();
    this.pivotValue = 0;

    this.collection_id = collection_id;
    this.collection_name = collection_name;
    this.serverInstance = server;
    this.flags = flags;
    this.storageInstance = new MMKV({
      id: `${this.uniqueId(this.collectionName)}-mmkv`,
      encryptionKey: collection_name
    });

    if (this.isPivot) {
      this.getPivotServer().then((pivot) => {
        this.pivot = pivot;
      });
    } else {
      this.getIdSetServer().then((list) => {
        this.idSet = list;
      });
    }
  }

  /**
   * @returns the name of the collection id
   */
  public get collectionId() {
    return this.collection_id;
  }

  /**
   * @returns the collection name
   */
  public get collectionName() {
    return this.collection_name;
  }

  /**
   * @returns the name of the ID list name for the collection
   */
  public get idSetCollectionName() {
    return BaseController.id_list_collection_name;
  }

  /**
   * @returns the firestore document for the ID set of the collection
   */
  public get idSetDocument() {
    return this.server
      .collection(this.idSetCollectionName)
      .doc(this.collectionName);
  }

  /**
   * @returns the firestore instance
   */
  public get server() {
    return this.serverInstance();
  }

  /**
   * @returns the firestore wrapper instance
   */
  public get metaServer() {
    return this.serverInstance;
  }

  /**
   * @returns the firestore collection
   */
  public get collection() {
    return this.server.collection(this.collectionName);
  }

  /**
   * @returns the MMKV storage instance
   */
  public get storage() {
    return this.storageInstance;
  }

  /**
   * @returns true if the controller requires a trail
   */
  public get hasTrail(): boolean {
    return (this.flags & ControllerFlag.has_trail) !== 0;
  }

  /**
   * @returns true if the controller uses a pivot instead of ID set
   */
  public get isPivot(): boolean {
    return (this.flags & ControllerFlag.pivot_not_list) !== 0;
  }

  /**
   * @returns true if the controller can deactivate entities
   */
  public get canDeactivate(): boolean {
    return (this.flags & ControllerFlag.can_deactivate) !== 0;
  }

  /**
   * @returns true if the controller can delete entities
   */
  public get canDelete(): boolean {
    return (this.flags & ControllerFlag.can_delete) !== 0;
  }

  /**
   * @returns true if the controller can update entities
   */
  public get canUpdate(): boolean {
    return (this.flags & ControllerFlag.can_update) !== 0;
  }

  /**
   * The document is automatically added to cache.
   *
   * @param id of the document to be fetched
   * @returns the document instance as is with its meta-data
   * @protected
   */
  protected async getServer(id: string) {
    const document = await this.collection.doc(id).get();

    if (document.exists) {
      this.setCache(id, document.data() as RawData);
    }

    return document;
  }

  /**
   * No need to update cache; automatically updated by listener.
   *
   * @param data of the new document to be created on server
   * @param id of the document. If not given, generated by firebase
   * @returns the ID of the new object if the ID is auto-generated
   * @protected
   */
  protected async createServer(id: string, data: RawData) {
    this.cleanData(data);
    await this.collection.doc(id).set(data);
    this.addId(id);
  }

  /**
   * No need to update cache; automatically updated by listener.
   *
   * @param data updated data of the document
   * @param id of the document to be updated
   * @param noStamp boolean flag, true indicates that the update
   *        is for deactivation.
   * @protected
   */
  protected async updateServer(data: Generic, id: string, noStamp?: boolean) {
    noStamp = noStamp ?? false;

    if (!(this.canUpdate || noStamp)) {
      throw new NoUpdateError();
    }

    if (!noStamp) {
      this.stamp(data[SpecialFields.trail], TrailNature.U);
    }

    this.cleanData(data);

    await this.runTransaction(
      async (transaction) => {
      transaction.update(this.collection.doc(id), data);
    });
  }

  /**
   * No need to update cache; automatically updated by listener.
   * This function may not be used.
   *
   * @param id to be deleted completely
   * @protected
   */
  public async removeServer(id: string) {
    if (!this.canDelete) {
      throw new NoDeleteError();
    }

    this.removeId(id);
    await this.collection.doc(id).delete();
  }

  /**
   * @param ids to be completely deleted
   * @throws NoDeleteError if the controller does not allow deletes
   */
  public async removeAllFromServer(ids: [string, ...string[]]) {
    if (!this.canDelete) {
      throw new NoDeleteError();
    }

    for (let id of ids) {
      await this.removeServer(id);
    }

    await this.uploadIds();
  }

  /**
   * @param id of the document to be marked as deactivated
   * @throws NoDeactivateError if the controller does not allow deactivation
   * @throws NoTrailError if the controller does not allow trails
   * @protected
   */
  public async deactivate(id: string) {
    if (!this.canDeactivate) {
      throw new NoDeactivateError();
    } else if (!this.hasTrail) {
      throw new NoTrailError();
    }

    const data = await this.getData(id);

    if (data === undefined) {
      throw new NoDataError();
    }

    this.stamp(data[SpecialFields.trail], TrailNature.D);

    await this.updateServer(data, id, true);
  }

  /**
   * @param trail to be stamped
   * @param nature of the action
   * @protected
   */
  protected stamp(trail: TrailType, nature: TrailNature) {
    if (this.hasTrail) {
      BaseModel.stamp(trail, nature);
    }
  }

  /**
   * @param id of the document to be marked as reactivated
   * @throws NoDeactivateError if the controller does not allow deactivation
   * @throws NoTrailError if the controller does not allow trails
   * @protected
   */
  public async reactivate(id: string) {
    if (!this.canDeactivate) {
      throw new NoDeactivateError();
    } else if (!this.hasTrail) {
      throw new NoTrailError();
    }

    const data = await this.getData(id);

    if (data === undefined) {
      throw new NoDataError();
    }

    this.stamp(data[SpecialFields.trail], TrailNature.R);

    await this.updateServer(data, id, true);
  }

  /**
   * @param id of the document to be erased
   * @throws IdDoesNotExistError if the controller does not allow deactivation
   * @throws NoTrailError if the controller does not allow trails
   * @protected
   */
  public async erase(id: string) {
    if (!this.canDelete) {
      throw new NoDeactivateError();
    } else if (await this.isIdAvailable(id)) {
      throw new IdDoesNotExistError();
    } else if (!this.hasTrail) {
      throw new NoTrailError();
    }

    const data = await this.getData(id);

    if (data === undefined) {
      throw new NoDataError();
    }

    const newData = {
      [SpecialFields.trail]: data[SpecialFields.trail]
    };

    this.stamp(newData[SpecialFields.trail], TrailNature.E);

    await this.collection.doc(id).set(newData);
  }

  /**
   * @param id to be checked
   * @returns true if there is no document belonging to the ID
   * @protected
   */
  public async isIdAvailable(id: string) {
    if (this.checkCache(id)) {
      return await this.isErased(id);
    }

    if (!this.isPivot) {
      return !(id in this.idSet) || await this.isErased(id);
    }

    return true;
  }

  /**
   * @param id to be checked
   * @returns true if the document related to the ID is erase, otherwise false.
   * @private
   */
  private async isErased(id: string): Promise<boolean> {
    const data = await this.getData(id);

    if (data === undefined) {
      return true;
    }

    return BaseModel.isDeleted(data[SpecialFields.trail]);
  }

  /**
   * @param id to be checked
   * @returns true iff the document is deactivated
   * @private
   */
  public async isDeactivated(id: string): Promise<boolean> {
    const data = await this.getData(id);

    if (data === undefined) {
      return false;
    }

    return BaseModel.isDeactivated(data[SpecialFields.trail]);
  }

  /**
   * Activates the listener for the collection.
   * Handles update processing between documents.
   * This is the default implementation of the listener activation.
   * Child classes will need to override it.
   *
   * @private
   */
  protected activateListener() {
    this.collection.onSnapshot(snapshot => {
      snapshot.docChanges().forEach(async (change) => {
        const document = change.doc;
        const data: RawData = document.data() as RawData;
        const id = document.id;

        if (change.type === "added") {
          this.setCache(id, data);
        } else if (change.type === "modified") {
          this.updateCache(id, data);
        } else if (change.type === "removed") {
          this.removeCache(id);
        }
      });
    });
  }

  /**
   * Triggers the RN hook for front-end updates.
   * @protected
   */
  protected triggerHook(): void {
    // TODO solve issue using redux
    // this.hook.setter(!this.hook.variable);
  }

  /**
   * @param id to be checked
   * @returns true if the ID is in cache
   * @protected
   */
  protected checkCache(id: string): boolean {
    return this.storage.contains(id);
  }

  /**
   * @param id to be fetched from cache
   * @returns undefined if the document does not exist,
   *          or the document of the ID.
   * @protected
   */
  protected getCache(id: string): RawData | undefined {
    if (this.checkCache(id)) {
      let result = JSON.parse(this.storage.getString(id) as string);

      result[this.collectionId] = id;

      return result;
    }

    return undefined;
  }

  /**
   * Triggers hook. Overrides any data.
   *
   * @param id ID of the document
   * @param data raw data of the document
   * @protected
   */
  protected setCache(id: string, data: RawData): void {
    this.updateSearchEngine(id, data).then(() => {
      this.storage.set(id, JSON.stringify(data));
      this.triggerHook();
    });
  }

  /**
   * Triggers hook. Updates only values in data
   *
   * @param id ID of the document
   * @param data raw data of the document
   * @protected
   */
  protected updateCache(id: string, data: Generic): void {
    let oldData: Generic = this.getCache(id) ?? {};

    for (let key of Object.keys(data)) {
      oldData[key] = data[key];
    }

    this.setCache(id, oldData as RawData);
  }

  /**
   * @param json_0 first object
   * @param json_1 second object
   * @returns Set containing the keys of both objects
   * @private
   */
  public static joinKeys(json_0: Generic,
                         json_1: Generic): Set<string> {
    let result = new Set<string>(Object.keys(json_0));

    for (let key of Object.keys(json_1)) {
      result.add(key);
    }

    return result;
  }

  /**
   * @param id to be removed from the search engine
   * @protected
   */
  protected async removeFromSearchEngine(id: string) {
    if (this.searchEngine === undefined) {
      return;
    }

    const data = this.getCache(id);

    if (data === undefined) {
      throw new NoDataError();
    }

    await remove(this.searchEngine, this.idToOramaId[id]);
    delete this.idToOramaId[id];
  }

  /**
   * Triggers hook
   *
   * @param id to be deleted from cache.
   * @protected
   */
  protected removeCache(id: string): void {
    this.removeFromSearchEngine(id).then(() => {
      this.storage.delete(id);
      this.triggerHook();
    });
  }

  /**
   * If the document is in cache, fetch it.
   * Otherwise, fetch the document from the server, save it to cache.
   *
   * @param id ID of the document to be fetched.
   * @protected
   */
  protected async getData(id: string): Promise<RawData | undefined> {
    if (this.checkCache(id)) {
      return this.getCache(id);
    }

    return (await this.getServer(id)).data() as RawData;
  }

  /**
   * @param id to be added to the ID list on server
   */
  public addId(id: string) {
    if (this.isPivot) {
      if (!isInteger(id)) {
        throw new PivotError();
      }

      this.pivot = Number(id);
    } else {
      this.idSet.add(id);
    }
  }

  /**
   * @param id to be removed from the ID list on server
   */
  public removeId(id: string) {
    if (!this.isPivot) {
      this.idSet.delete(id);
    }
  }

  /**
   * @returns a list of IDs in the collection.
   *          This list is suitable for upload.
   * @private
   */
  private get idSetUpload() {
    return Array.from<string>(this.idSet.values());
  }

  /**
   * Performs the given transaction function to the server.
   * Returns its result.
   *
   * @param body transaction function to be run
   * @returns transaction result if any
   */
  public async runTransaction(body:
      (transaction: FirebaseFirestoreTypes.Transaction) => any) {
    return await this.server.runTransaction(body);
  }

  /**
   * Updates the ID set of the collection on server.
   * If the controller uses a pivot system, upload the pivot.
   */
  public async uploadIds() {
    await this.runTransaction(async (transaction) => {
      transaction.set(this.idSetDocument, {
        data: this.isPivot ? this.pivot : this.idSetUpload
      });
    });
  }

  /**
   * @returns the ID set of the collection
   */
  public get idSet() {
    return this.idSetInstance;
  }

  /**
   * @param value new set of IDs
   */
  public set idSet(value) {
    this.idSetInstance = value;
  }

  /**
   * @returns the current storred local pivot
   */
  public get pivot() {
    return this.pivotValue;
  }

  /**
   * @param value new pivot value
   */
  public set pivot(value) {
    this.pivotValue = value;
  }

  /**
   * @returns the collection pivot from the server
   * @private
   */
  private async getPivotServer(): Promise<number> {
    const document = await this.idSetDocument.get();

    if (!document.exists) {
      return this.pivot;
    }

    return document.data()?.data;
  }

  /**
   * @returns a list containing all document IDs in a collection
   */
  private async getIdSetServer(): Promise<Set<string>> {
    const document = await this.idSetDocument.get();

    if (!document.exists) {
      return this.idSet;
    }

    // Check server upload for naming if needed
    return new Set<string>(document.data()?.data);
  }

  /**
   * Clears the cache completely
   */
  public clearCache(): void {
    this.storage.clearAll();
  }

  /**
   * If there is no search engine, do nothing.
   * Default implementation of the load search for controllers.
   * Child classes might override and call in constructor.
   * @protected
   */
  protected async loadSearchData() {
    if (this.searchEngine === undefined) {
      return;
    }

    for (let id of this.storage.getAllKeys()) {
      const data = this.getCache(id);

      if (data === undefined) {
        continue;
      }

      await this.updateSearchEngine(id, data);
    }
  }

  /**
   * If there is no search engine, do nothing.
   *
   * @param id of the document
   * @param data to be inserted into the search engine
   * @protected
   */
  protected async updateSearchEngine(id: string, data: RawData) {
    if (this.searchEngine === undefined) {
      return;
    }

    this.idToOramaId[id] = await insert(this.searchEngine, data);
  }

  /**
   * @returns the initial trail type for any document
   * @protected
   */
  protected generateInitialTrail(): TrailType {
    let result = {};

    this.stamp(result, TrailNature.C);

    return result;
  }

  /**
   * @param data to be cleaned
   * @private
   */
  private cleanData(data: Generic) {
    if (this.collectionId in data) {
      delete data[this.collectionId];
    }
  }

  /**
   * @returns a unique application ID for the controller
   */
  public uniqueId(collection_name: string) {
    return `${this.metaServer.name}-${collection_name}`;
  }

  /**
   * Injects the controller into redux to be used by other components
   */
  public injectDependency(): void {
    // reduxStorage.setItem(this.uniqueId(this.collectionName),
    //   JSON.stringify(this));
  }

  /**
   * @param collection_name to be taken from dependency
   * @returns the controller responsible for the collection
   */
  public getDependency(collection_name: string): any {
    return reduxStorage.getItem(this.uniqueId(collection_name));
  }

  /**
   * @param data to be formatted for creation
   * @returns data that has all undefined fields removed
   * @protected
   */
  protected fixDataGaps(data: Generic): RawData {
    return pickBy(data, identity) as RawData;
  }

  /**
   * @param id of the document to be fetched
   * @returns a BaseModel instance encapsulating the data
   */
  public abstract get(id: string): Promise<BaseModel>;

  /**
   *
   * @param model new model of the document
   */
  public abstract update(model: BaseModel): Promise<any>;

  /**
   * @param data basic data of the document
   */
  public abstract create(data: Generic): Promise<any>;

  /**
   * @param data raw data from user input
   * @returns raw data suitable for upload
   * @protected
   */
  protected abstract fillDataGaps(data: Generic): RawData;

  /**
   * @param data to be cleaned
   * @param newData data will be compared to
   * @protected
   */
  protected static clearAlikeFieldsFromNew(data: Generic, newData: Generic): void {
    for (let key of Object.keys(data)) {
      if (key === SpecialFields.trail) {
        continue;
      }

      if (isEqual(data[key], newData[key]) || newData[key] === undefined) {
        delete newData[key];
      }
    }
  }

  /**
   * This update-function is generalized.
   * Works for most controllers.
   *
   * @param model new model of the document
   * @param id of the document
   */
  protected async genericUpdate(model: BaseModel, id: string): Promise<void> {
    if (await this.isIdAvailable(id)) {
      throw new IdDoesNotExistError();
    }

    const currentData: Generic | undefined = this.getCache(id);
    const data: Generic = model.dataCopy;

    if (currentData === undefined) {
      await this.updateServer(data, id);
      return;
    }

    BaseController.clearAlikeFieldsFromNew(currentData, data);

    await this.updateServer(data, id);
  }

  /**
   * This get-function is generalized.
   * Works for most controllers.
   *
   * @param ctor BaseModel constructor
   * @param id of the document
   * @returns BaseModel instance for the controller
   * @protected
   */
  protected async genericGet<T extends BaseModel>(
    ctor: new (...arg: any) => T,
    id: string): Promise<T> {
    const data = await this.getData(id);

    if (data === undefined) {
      throw new IdDoesNotExistError();
    }

    return new ctor(data);
  }

  /**
   * This create-function is generalized.
   * Works for most controllers.
   *
   * @param data raw data to be used
   * @param id new ID of the document
   * @protected
   */
  protected async genericCreate(data: Generic, id: string): Promise<void> {
    if (!(await this.isIdAvailable(id))) {
      throw new IdAlreadyExistsError();
    }

    await this.createServer(id, this.fillDataGaps(data));
    await this.uploadIds();
  }
}
