import firestore from "@react-native-firebase/firestore";
import { MMKV } from "react-native-mmkv";
import { create, insert, Orama, ProvidedTypes, remove, Schema } from "@orama/orama";
import { IdDoesNotExistError, NoDataError, NoDeactivateError, NoDeleteError, NoUpdateError } from "./Errors";
import { TrailNature, TrailType } from "../model/types";
import BaseModel from "../model/BaseModel";
import CollectionNames from "./CollectionNames";
import { identity, pickBy } from "lodash";
import { reduxStorage } from "../../../store";


/* Flags to specify the capabilities of a controller */
export enum ControllerFlag {
  has_trail =       0b0001,
  can_deactivate =  0b0010,
  can_delete =      0b0100,
  can_update =      0b1000,
}

/* Generic Object type */
export type Generic = {
  [id: string]: any
};

/**
 * Class responsible for handling raw data storage & retrieval
 * from the cache and database.
 * Forms the base class for the rest of the controllers.
 */
export default abstract class BaseController<RawData extends Generic> {
  /* collection name */
  private readonly collection_name: string;

  /* name of the ID list collection */
  private static readonly id_list_collection_name: string = CollectionNames.ids;

  /* name of the data field representing a document ID */
  private readonly collection_id: string;

  /* firestore instance representing the database */
  private readonly serverInstance: typeof firestore;

  /* MMKV storage instance used for the controllers */
  private readonly storageInstance: MMKV;

  /* sett of all collection IDs */
  private idSetInstance: Set<string>;

  /* flags variable generated by applying logical or on Flag enums */
  private readonly flags: number;

  /* search engine instance for the controller */
  public searchEngine?: Orama<ProvidedTypes>;

  /* maps document IDs to Orama IDs */
  private idToOramaId: {
    [id: string]: any
  } = {};

  /**
   * @param collection_name name of the controlled collection
   * @param collection_id name of the data field
   *        that acts as an ID for the document.
   *        This field is removed from raw data on upload & download.
   * @param server firestore instance for the database
   * @param search_schema for the search engine
   * @param flags number representing capabilities of controller
   */
  protected constructor(collection_name: string,
              collection_id: string,
              server: typeof firestore,
              flags: number = 0,
              search_schema?: Schema) {
    if (search_schema !== undefined) {
      create({
        schema: search_schema,
        id: collection_name
      }).then((value) => {
        this.searchEngine = value;
      });
    }

    this.idSetInstance = new Set<string>();
    this.collection_id = collection_id;
    this.collection_name = collection_name;
    this.serverInstance = server;
    this.flags = flags;
    this.storageInstance = new MMKV({
      id: `${this.uniqueId(this.collectionName)}-mmkv`,
      encryptionKey: collection_name
    });

    this.getIdSetServer().then((list) => {
      this.idSet = list;
    });
  }

  /**
   * @returns the name of the collection id
   */
  public get collectionId() {
    return this.collection_id;
  }

  /**
   * @returns the collection name
   */
  public get collectionName() {
    return this.collection_name;
  }

  /**
   * @returns the name of the ID list name for the collection
   */
  public get idSetCollectionName() {
    return BaseController.id_list_collection_name;
  }

  /**
   * @returns the firestore document for the ID set of the collection
   */
  public get idSetDocument() {
    return this.server
      .collection(this.idSetCollectionName)
      .doc(this.collectionName);
  }

  /**
   * @returns the firestore instance
   */
  public get server() {
    return this.serverInstance();
  }

  /**
   * @returns the firestore wrapper instance
   */
  public get metaServer() {
    return this.serverInstance;
  }

  /**
   * @returns the firestore collection
   */
  public get collection() {
    return this.server.collection(this.collectionName);
  }

  /**
   * @returns the MMKV storage instance
   */
  public get storage() {
    return this.storageInstance;
  }

  /**
   * @returns true if the controller requires a trail
   */
  public get hasTrail(): boolean {
    return (this.flags & ControllerFlag.has_trail) !== 0;
  }

  /**
   * @returns true if the controller can deactivate entities
   */
  public get canDeactivate(): boolean {
    return (this.flags & ControllerFlag.can_deactivate) !== 0;
  }

  /**
   * @returns true if the controller can delete entities
   */
  public get canDelete(): boolean {
    return (this.flags & ControllerFlag.can_delete) !== 0;
  }

  /**
   * @returns true if the controller can update entities
   */
  public get canUpdate(): boolean {
    return (this.flags & ControllerFlag.can_update) !== 0;
  }

  /**
   * The document is automatically added to cache.
   *
   * @param id of the document to be fetched
   * @returns the document instance as is with its meta-data
   * @protected
   */
  protected async getServer(id: string) {
    const document = await this.collection.doc(id).get();

    if (document.exists) {
      this.setCache(id, document.data() as RawData);
    }

    return document;
  }

  /**
   * No need to update cache; automatically updated by listener.
   *
   * @param data of the new document to be created on server
   * @param id of the document. If not given, generated by firebase
   * @returns the ID of the new object if the ID is auto-generated
   * @protected
   */
  protected async createServer(id: string, data: RawData) {
    this.cleanData(data);
    await this.collection.doc(id).set(data);
    this.addId(id);
  }

  /**
   * No need to update cache; automatically updated by listener.
   *
   * @param data updated data of the document
   * @param id of the document to be updated
   * @param noStamp boolean flag, true indicates that the update
   *        is for deactivation.
   * @protected
   */
  protected async updateServer(data: Generic, id: string, noStamp?: boolean) {
    noStamp = noStamp ?? false;

    if (!(this.canUpdate || noStamp)) {
      throw new NoUpdateError();
    }

    if (!noStamp) {
      BaseModel.stamp(data.trail, TrailNature.U);
    }

    this.cleanData(data);

    await this.server.runTransaction(
      async (transaction) => {
      transaction.update(this.collection.doc(id), data);
    });
  }

  /**
   * No need to update cache; automatically updated by listener.
   * This function may not be used.
   *
   * @param id to be deleted completely
   * @protected
   */
  protected async removeServer(id: string) {
    if (!this.canDelete) {
      throw new NoDeleteError();
    }

    this.removeId(id);
    await this.collection.doc(id).delete();
  }

  /**
   * @param ids to be completely deleted
   */
  public async delete(ids: [string, ...string[]]) {
    for (let id of ids) {
      await this.removeServer(id);
    }

    await this.uploadIds();
  }

  /**
   * @param id of the document to be marked as deactivated
   * @protected
   */
  public async deactivate(id: string) {
    if (!this.canDeactivate) {
      throw new NoDeactivateError();
    }

    const data = await this.getData(id);

    if (data === undefined) {
      throw new NoDataError();
    }

    BaseModel.stamp(data.trail, TrailNature.D);

    await this.updateServer(data, id, true);
  }

  /**
   * @param id of the document to be marked as reactivated
   * @protected
   */
  public async reactivate(id: string) {
    if (!this.canDeactivate) {
      throw new NoDeactivateError();
    }

    const data = await this.getData(id);

    if (data === undefined) {
      throw new NoDataError();
    }

    BaseModel.stamp(data.trail, TrailNature.R);

    await this.updateServer(data, id, true);
  }

  /**
   * @param id of the document to be erased
   * @protected
   */
  public async erase(id: string) {
    if (!this.canDelete) {
      throw new NoDeactivateError();
    } else if (await this.isIdAvailable(id)) {
      throw new IdDoesNotExistError();
    }

    const data = await this.getData(id);

    if (data === undefined) {
      throw new NoDataError();
    }

    const newData = {
      trail: data.trail
    };

    BaseModel.stamp(newData.trail, TrailNature.E);

    await this.collection.doc(id).set(newData);
  }

  /**
   * @param id to be checked
   * @returns true if there is no document belonging to the ID
   * @protected
   */
  public async isIdAvailable(id: string) {
    if (this.checkCache(id)) {
      return await this.isErased(id);
    }

    return !(id in this.idSet) || await this.isErased(id);
  }

  /**
   * @param id to be checked
   * @returns true if the document related to the ID is erase, otherwise false.
   * @private
   */
  private async isErased(id: string): Promise<boolean> {
    const data = await this.getData(id);

    if (data === undefined) {
      return true;
    }

    return BaseModel.isDeleted(data.trail);
  }

  /**
   * @param id to be checked
   * @returns true iff the document is deactivated
   * @private
   */
  public async isDeactivated(id: string): Promise<boolean> {
    const data = await this.getData(id);

    if (data === undefined) {
      return false;
    }

    return BaseModel.isDeactivated(data.trail);
  }

  /**
   * Activates the listener for the collection.
   * Handles update processing between documents.
   * This is the default implementation of the listener activation.
   * Child classes will need to override it.
   *
   * @private
   */
  protected activateListener() {
    this.collection.onSnapshot(snapshot => {
      snapshot.docChanges().forEach(async (change) => {
        const document = change.doc;
        const data: RawData = document.data() as RawData;
        const id = document.id;

        if (change.type === "added") {
          this.setCache(id, data);
        } else if (change.type === "modified") {
          this.updateCache(id, data);
        } else if (change.type === "removed") {
          this.removeCache(id);
        }
      });
    });
  }

  /**
   * Triggers the RN hook for front-end updates.
   * @protected
   */
  protected triggerHook(): void {
    // TODO solve issue using redux
    // this.hook.setter(!this.hook.variable);
  }

  /**
   * @param id to be checked
   * @returns true if the ID is in cache
   * @protected
   */
  protected checkCache(id: string): boolean {
    return this.storage.contains(id);
  }

  /**
   * @param id to be fetched from cache
   * @returns undefined if the document does not exist,
   *          or the document of the ID.
   * @protected
   */
  protected getCache(id: string): RawData | undefined {
    if (this.checkCache(id)) {
      let result = JSON.parse(this.storage.getString(id) as string);

      result[this.collectionId] = id;

      return result;
    }

    return undefined;
  }

  /**
   * Triggers hook. Overrides any data.
   *
   * @param id ID of the document
   * @param data raw data of the document
   * @protected
   */
  protected setCache(id: string, data: RawData): void {
    this.updateSearchEngine(id, data).then(() => {
      this.storage.set(id, JSON.stringify(data));
      this.triggerHook();
    });
  }

  /**
   * Triggers hook. Updates only values in data
   *
   * @param id ID of the document
   * @param data raw data of the document
   * @protected
   */
  protected updateCache(id: string, data: Generic): void {
    let oldData: Generic = this.getCache(id) ?? {};

    for (let key of Object.keys(data)) {
      oldData[key] = data[key];
    }

    this.setCache(id, oldData as RawData);
  }

  /**
   * @param id to be removed from the search engine
   * @protected
   */
  protected async removeFromSearchEngine(id: string) {
    if (this.searchEngine === undefined) {
      return;
    }

    const data = this.getCache(id);

    if (data === undefined) {
      throw new NoDataError();
    }

    await remove(this.searchEngine, this.idToOramaId[id]);
    delete this.idToOramaId[id];
  }

  /**
   * Triggers hook
   *
   * @param id to be deleted from cache.
   * @protected
   */
  protected removeCache(id: string): void {
    this.removeFromSearchEngine(id).then(() => {
      this.storage.delete(id);
      this.triggerHook();
    });
  }

  /**
   * If the document is in cache, fetch it.
   * Otherwise, fetch the document from the server, save it to cache.
   *
   * @param id ID of the document to be fetched.
   * @protected
   */
  protected async getData(id: string): Promise<RawData | undefined> {
    if (this.checkCache(id)) {
      return this.getCache(id);
    }

    return (await this.getServer(id)).data() as RawData;
  }

  /**
   * @param id to be added to the ID list on server
   */
  public addId(id: string) {
    this.idSet.add(id);
  }

  /**
   * @param id to be removed from the ID list on server
   */
  public removeId(id: string) {
      this.idSet.delete(id);
  }

  /**
   * @returns a list of IDs in the collection.
   *          This list is suitable for upload.
   * @private
   */
  private get idSetUpload() {
    return Array.from<string>(this.idSet.values());
  }

  /**
   * Updates the ID set of the collection on server
   */
  public async uploadIds() {
    await this.server.runTransaction(
      async (transaction) => {
        transaction.set(this.idSetDocument, {
          data: this.idSetUpload
        });
    });
  }

  /**
   * @returns the ID set of the collection
   */
  public get idSet() {
    return this.idSetInstance;
  }

  /**
   * @param value new set of IDs
   */
  public set idSet(value) {
    this.idSetInstance = value;
  }

  /**
   * @returns a list containing all document IDs in a collection
   */
  private async getIdSetServer(): Promise<Set<string>> {
    const document = await this.idSetDocument.get();

    if (!document.exists) {
      return this.idSet;
    }

    // Check server upload for naming if needed
    return new Set<string>(document.data()?.data);
  }

  /**
   * Clears the cache completely
   */
  public clearCache(): void {
    this.storage.clearAll();
  }

  /**
   * If there is no search engine, do nothing.
   * Default implementation of the load search for controllers.
   * Child classes might override and call in constructor.
   * @protected
   */
  protected async loadSearchData() {
    if (this.searchEngine === undefined) {
      return;
    }

    for (let id of this.storage.getAllKeys()) {
      const data = this.getCache(id);

      if (data === undefined) {
        continue;
      }

      await this.updateSearchEngine(id, data);
    }
  }

  /**
   * If there is no search engine, do nothing.
   *
   * @param id of the document
   * @param data to be inserted into the search engine
   * @protected
   */
  protected async updateSearchEngine(id: string, data: RawData) {
    if (this.searchEngine === undefined) {
      return;
    }

    this.idToOramaId[id] = await insert(this.searchEngine, data);
  }

  /**
   * @returns the initial trail type for any document
   * @protected
   */
  protected generateInitialTrail(): TrailType {
    let result = {};

    BaseModel.stamp(result, TrailNature.C);

    return result;
  }

  /**
   * @param data to be cleaned
   * @private
   */
  private cleanData(data: Generic) {
    if (this.collectionId in data) {
      delete data[this.collectionId];
    }
  }

  /**
   * @returns a unique application ID for the controller
   */
  public uniqueId(collection_name: string) {
    return `${this.metaServer.name}-${collection_name}`;
  }

  /**
   * Injects the controller into redux to be used by other components
   */
  public injectDependency(): void {
    reduxStorage.setItem(this.uniqueId(this.collectionName), this);
  }

  /**
   * @param collection_name to be taken from dependency
   * @returns the controller responsible for the collection
   */
  public getDependency(collection_name: string): any {
    return reduxStorage.getItem(this.uniqueId(collection_name));
  }

  /**
   * @param data to be formatted for creation
   * @returns data that has all undefined fields removed
   * @protected
   */
  protected fillDataGaps(data: Generic): RawData {
    return pickBy(data, identity) as RawData;
  }

  /**
   * @param id of the document to be fetched
   * @returns a BaseModel instance encapsulating the data
   */
  public abstract get(id: string): Promise<BaseModel>;

  /**
   * @param data new data of the document
   */
  public abstract update(data: BaseModel): Promise<any>;

  /**
   * @param data basic data of the document
   */
  public abstract create(data: Generic): Promise<any>;
}
